import setuptools

setuptools.setup(
    use_scm_version={
        "write_to": "src/ocnewrelic/version.py",
        "write_to_template": """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = "{version!s}"
""",
    }
)
